#!/bin/bash
# Basically: cd lis; ./configure; ./compile -j 4

MYPWD=$(pwd)

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $ROOT

declare -A submodules
submodules[0]='ldt'
submodules[1]='lis'

# load the modules
source load_modules

echo -n "Please enter the submodule to build (0-ldt, 1-lis, default: 1): "
read submodule
submodule=${submodules[${submodule:-1}]}
cd $submodule

# run configure and accept defaults or change to 'debug' compilation if wanted
./configure

echo -n "Please enter how to compile (0-batch, 1-interactive, default: 1): "
read mode
mode=${mode:-1}
echo -n "Please enter how many processes to use to compile (default: 8): "
read c
c=${c:-8}
if [[ $mode -eq 1 ]]; then
    ./compile -j $c
else
    opts=""
    if [[ "$VSC_INSTITUTE_CLUSTER" == "genius" || "$VSC_INSTITUTE_CLUSTER" == "wice" ]]; then
        echo -n "Please enter the cluster on which to compile (default: cluster's default): "
        read M
        if [ -n "$M" ]; then
            opts="$opts -M $M"
        fi
        A="lp_ees_swm_ls_001"
    elif [[ "$VSC_INSTITUTE_CLUSTER" == "dodrio" ]]; then
        A="2022_203"
    fi
    echo -n "Please enter the partition on which to compile (default: cluster's default): "
    read p
    if [ -n "$p" ]; then
        opts="$opts -p $p"
    fi

    cmd="sbatch -A $A $opts -c $c ../compile.slurm"
    echo $cmd
    $cmd
fi

cd $MYPWD
