#! /bin/bash

# To compile ldt or lis, run
source easybuild
# This will subsequently load the LISF module, call configure and call compile (in a batch job or interactively)
# This should work on the genius, wice and dodrio clusters.
# You can simply accept all defaults.
# Not all alternatives are supported (like HDF4)
# Change to 'debug' compilation if needed


# If you have already compiled and only need to load the LISF module, run
source load_modules
